version: '3'
services:
  
  #PHP Service
  app_emb:
    build:
      context: .
      dockerfile: Dockerfile
   # image: digitalocean.com/php
    container_name: app_emb
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app_emb
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
         - ./:/var/www 
         #- ./docker/use/php/php.ini-development:/usr/local/etc/php/php.ini
    #    - ../../testn.php :/var/www/public/testn.php
     #  - ./../../.env:/var/www/.env
      
    networks:
      - app-network-emb
    

  #Nginx Service
  web_emb:
    image: nginx:alpine
    platform: linux/x86_64
    restart: unless-stopped
    container_name: web_emb
    tty: true
    ports:
      - "801:80"
      - "802:80"
      - "803:80"
      - "804:80"
      - "805:80"
      - "447:443"
    volumes:
      - ./:/var/www
      - ./share/conf.d/nginxs.conf:/etc/nginx/conf.d/default.conf
     # - ./share/conf.d/default.nginx.conf:/etc/nginx/conf.d/default.conf
     # - ./share/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
     # - ./share/conf.d/nginx:/etc/nginx/nginx.conf
   #   - ./testn.php :/var/www/public/index.php
    #  - ../../testn.html :/var/www/public/index.html
    depends_on: 
        - app_emb
        - db_emb
    networks:
      - app-network-emb

  #MySQL Service
  db_emb:
    image: mysql:8.0.11
    platform: linux/x86_64
    container_name: db_emb
    restart: unless-stopped
    tty: true #eletypewriter
    ports:
      - "3309:3306"
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_emb
    volumes:
     # - ./.env:/var/www/.env
      - ./data_emb/mysql:/var/lib/mysql
    #   - ./docker/use/mysql/my.cnf:/etc/mysql/my.cnf 
    networks:
      - app-network-emb
   
  pma_emb:
        depends_on:
            - db_emb
        image: phpmyadmin/phpmyadmin
        container_name: pma_emb
        environment:
            - PMA_ARBITRARY= 1
            - PMA_HOST=db_emb
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
            - PMA_PORT=3306
      
        networks: 
          - app-network-emb
        ports:
            - 8888:80
#Docker Networks
networks:
  app-network-emb:
    driver: bridge
volumes:
  data_emb:
    #driver: local