#! /bin/bash
set -e



  [ -d "./site" ] && rm -r site/*

 function cloneRepo(){
   
    #sleep 2
    git clone https://github.com/azeez-abp/it-training-data.git /site
    #sleep 2
    #mv ./site/* .
    composer install
    sleep 2
    php artisan key:generate
    sleep 2
    #cp ./.env.cpanel ./.env
    sleep 2
    php artisan config:clear
    php artisan config:cache
    php artisan migrate
    touch .htaccess
echo "<ifModule mod_rewrite.c> 
    RewriteEngine on
    RewriteRule ^(.*) public/$1 [L] 
</ifModule>" > ./.htaccess

    
 }
 cloneRepo
#  if [[ `git --version =~ "(git version)+\D\d\.\d{2}\.+.+"` ]]
#  then
   
#   echo "CLONING DONE"
#  else 
#     #install git
#     echo "Git wil be intsall"
#      apt install git-all
#   fi


# git init --bare $HOME/.cfg
# alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
# config config --local status.showUntrackedFiles no
# echo "alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'" >> $HOME/.bashrc
